sudo: required
services:
  - docker

before_install:
  - docker build -t christian29/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true christian29/react-test npm test

after_success:
  - docker build -t christian29/multi-client ./client
  - docker build -t christian29/multi-nginx ./nginx
  - docker build -t christian29/multi-server ./server
  - docker build -t christian29/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push christian29/multi-client
  - docker push christian29/multi-nginx
  - docker push christian29/multi-server
  - docker push christian29/multi-worker